default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: rubytodo
  user: root
  password: 12345

production:
  <<: *default
  username: <%= ENV.fetch("DB_USERNAME") {""} %>
  password: <%= ENV.fetch("DB_PASSWORD") {""} %>
  database: rubytodo
  host:   <%= ENV.fetch("DB_SOCKET") {""} %>
